---
title: "RWorksheet #5"
author: "Krystal Rose M. Rizardo"
date: "2022-11-23"
output: pdf_document
---
```{r 1_A}


library(ggplot2)
data_ff <- data.frame("course"=c("1st", "2nd", "3rd", "4th"), "school_year"= c(80, 75, 70, 60))
ggplot(data_ff) + geom_col(aes(course, school_year))

school_year <- c(80, 75, 70, 60)
course <- c("1st", "2nd", "3rd", "4th")
```
```{r 1_B}
br <- barplot(school_year, main= "Enrollment of BS Computer Science",
              xlab = "Curriculum Year", ylab = "number of
              students")
```
```{r 2_A}
f <- 60
electric <- 10
savings <- 5
miscllaneous <- 25

dejesus_expenses <- data.frame(f, electric, savings,miscllaneous)
dejesus_expenses
```
```{r 2_B}
dejesus_exp <- c(60, 10, 5, 25)
pie(dejesus_exp, main = "Expenses", col = rainbow(length(dejesus_exp)),
    labels = c("f", "electric", "savings", "miscllaneous"))

expense_label <- round(dejesus_exp/sum(dejesus_exp) * 100, 1)
expense_label <- paste(expense_label, "%", sep = "")

pie(dejesus_exp, main = "Expenses", col = rainbow(length(dejesus_exp)),
    labels = expense_label, cex=0.8)
legend(1, c("food", "electricity", "savings", "misc"),
       cex = 0.8, fill = rainbow(length(dejesus_exp)))
```
```{r 3}
data("mtcars")

mt  <- mtcars$mpg

hist(mt, main = "Histogram for mpg")
```
```{r 3_B}
hist(mt, breaks=12, col="green")
```
```{r 3_C}
h<-hist(mt, breaks=10, col="green", xlab="Miles Per Gallon",
        main="Histogram with Normal Curve")
xfit<-seq(min(mt),max(mt),length=40)
yfit<-dnorm(xfit,mean=mean(mt),sd=sd(mt))
yfit <- yfit*diff(h$mids[1:2])*length(mt)
lines(xfit, yfit, col="red", lwd=2)
```
```{r 3_D}
data("iris")

data_iris <- data.frame(iris)
data_iris
setosa_data <- subset(data_iris, Species == 'setosa')
setosa_data

data_irisb <- data.frame(iris)
data_irisb
versi_data <- subset(data_irisb, Species == 'versicolor')
versi_data

data_irisc <- data.frame(iris)
data_irisc
vergi_data <-subset(data_irisc, Species == 'virginica')
vergi_data

```
```{r 4_B}
setosa <- colMeans(setosa_data[sapply(setosa_data,is.numeric)])
setosa

versicolor <- colMeans(versi_data[sapply(versi_data,is.numeric)])
versicolor

virginica <- colMeans(vergi_data[sapply(vergi_data,is.numeric)])
virginica
```
```{r 4_C}
combine <- rbind(setosa, versicolor, virginica)
combine

```
```{r 4_D}
barplot(combine, beside =TRUE, main = "Iris Mean",
        xlab = "Characterisics", ylab = "Mean Scores",
        col = c("green", "orange", "yellow"))
```