---
title: "RWorksheet2"
author: "Krystal Rose M. Rizardo"
date: "2022-10-07"
output: pdf_document
---



## R Markdown

```{r vector1A}
num <- seq(-5:5)
num
```
```{r vector1B}
x<- 1:7
x
```
```{r vector2}
l <- seq(1,3, by=0.2)
l
```

```{r vector3}
      cenlist <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27,
                     22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35,
                     24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26,
                     18)
      cenlist
```
        
```{r vector3A}
cenlist [3]
```       

``` {r vector3B}
cenlist [2]
cenlist [4]
```

```{r vector3C}
cenlist[2:50]
```
``` {r vector4}
names <- c("first"=3, "second"=3, "third"=9)
names 
```
``` {r vector4A}
names[c("first", "third")]
```
``` {r vector5}
x <- -3:2
x
```

``` {r vector6}
Month = c("Jan", "Feb", "March","April", "May","June")
Price_per_liter<- c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00)
Quantity <- c(25, 30, 40, 50, 10, 45)
```

``` {r vector6A}
Diesel<- data.frame (Month, Price_per_liter, Quantity)
Diesel
```
```{r vector6B}
weighted.mean(Price_per_liter,Quantity)
```
``` {r vector7A}
data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers),
          sd(rivers), min(rivers), max(rivers))
data
```
``` {r vector8A}
power_celeb <- 1:25
celeb_name <- c("Tom Cruise","Rolling Stones", "Oprah Winfrey","U2","Tiger Woods",
                   "Steven Spielberg","Howarf Stern","50 Cent","Cast of the Sopranos","Dan Brown",
                   "Bruce Springsteen", "Donald Trump","Muhammand Ali","Paul McCartney","George Lucas",
                   "Elton John","David Letterman","Phil Mickelson", "J.K Rowling","Bradd Pitt",
                   "Peter Jackson","Dr.Phil McGraw","Jay Lenon","Celine Dion","Kobe Bryan")
celeb_name
```


``` {r vector8AA}
Pay <- c(67, 90, 225,110,90,332,302,41,52,88,55,44,55,40,233,34,40,47,75,25,39,45,32,40,31)

Pay
```
               
``` {r vectors8AAA}
CelebrityAnnualPay <- data.frame(power_celeb,celeb_name,Pay)
CelebrityAnnualPay
```
``` {r vector9}
CelebrityAnnualPay [19, "power_celeb"] = 15
CelebrityAnnualPay[19, "Pay"] = 90
CelebrityAnnualPay
```
